title: "Thomas Rose"
description: "Data Analyst Portfolio"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Trose94.github.io" # the base hostname & protocol for your site
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Customization
author:
  name: "Thomas Rose"
  email: "your-email@example.com"
  bio: "Business Intelligence Analyst specializing in data analytics."
  avatar: "/assets/images/avatar.jpg" # Add your avatar image in the assets/images folder

# Social links
social:
  twitter: your_twitter_handle
  linkedin: your_linkedin_profile
  github: Trose94

# Google Analytics
google_analytics: UA-XXXXXXXX-X

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
