title: Thomas' Portfolio
email: your.email@example.com
description: >-
  Business Intelligence Analyst with experience in analytics, data modeling, and Python programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Trose94.github.io" # the base hostname & protocol for your site

theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

just_the_docs:
  # Enable dark mode
  color_scheme: dark

header_pages:
  - index.md

navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
