title: Thomas' Portfolio
email: your.email@example.com
description: >-
  Business Intelligence Analyst with experience in analytics, data modeling, and Python programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Trose94.github.io" # the base hostname & protocol for your site

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "Thomas"

header_pages:
  - index.md

navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"

# Minimal Mistakes Skin (Dark Mode)
minimal_mistakes_skin: "dark"

# Optional settings
# Show excerpts instead of full posts
show_excerpts: true

# Enable comments via Disqus (replace `your_disqus_shortname` with your Disqus shortname)
# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "your_disqus_shortname"

# Social media accounts (optional)
social:
  - name: "GitHub"
    url: "https://github.com/Trose94"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/your-linkedin-profile"
