# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Thomas' Portfolio
email: Thomasarose94@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Business Intelligence Analyst with experience in analytics, SQL, data modeling, and Python programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Trose94.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  Trose94


theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "Thomas"

# Minima includes some nice default headers.
header_pages:
  - index.md

# Use a navigation.yml file to control the header links
navigation: 
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"

# Enable dark mode
minimal_mistakes_skin: "dark"
